/**:
  ros__parameters:

  # Main node params
    publish_rate: 20.0 # milliseconds

  # Arm
    arm/axis.throttle: 3
    arm/axis.x: 1
    arm/axis.y: 0
    arm/button.home: 5
    arm/button.use_arm_mode: 0
    # movement speed multiplier, directly multiplied on
    arm/speed_multiplier: 20

  # Drive
    drive/axis.throttle: 3
    drive/axis.linear: 1
    drive/axis.angular: 2
    drive/button.disable: 3
    drive/button.enable: 2
    # maximum defaults (in case the robot doesn't publish it's values)
    drive/maximum.rpm: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    drive/maximum.vel.linear: [10.0, 0.0, 0.0]
    drive/maximum.vel.angular: [0.0, 0.0, 10.0]
  
    # rpm overrides
    drive/rpm_override_count: 2

    drive/rpm_override_0.button_forward: 9
    drive/rpm_override_0.button_backward: 8
    drive/rpm_override_0.speed_multiplier: 0.5
    drive/rpm_override_0.overrides_motors: [ 0, -1] # negative = inverted

    drive/rpm_override_1.button_forward: 11
    drive/rpm_override_1.button_backward: 10
    drive/rpm_override_1.speed_multiplier: 0.5
    drive/rpm_override_1.overrides_motors: [ -6, 7]
